blank_issues_enabled: true
contact_links:
  - name: 💬 Ideias & Discussões Gerais
    url: https://github.com/millersantosbr/Vou-de-Van-Alagoas/discussions
    about: Quer bater um papo aberto sobre transporte em Alagoas ou sugerir algo informalmente?
